### PR TITLE
Fix Github actions badge

### PR DESCRIPTION
**Pull request by mblue9**
The badge is showing the build as failing when it's not, fixed here.

### CODE REVIEW

**Comment by mblue9** [comment]
Weird permissions error here with the Mac build. Could you try pushing a commit to this PR to see if you have permission?
```
    NotWritableError: The current user does not have write permissions to a required path.
      path: /usr/local/miniconda/pkgs/cache/b89cf7bf.json
      uid: 501
      gid: 20
```

**Comment by stemangiola** [comment]
> 
> 
> Weird permissions error here with the Mac build. Could you try pushing a commit to this PR to see if you have permission?
> 
> ```
>     NotWritableError: The current user does not have write permissions to a required path.
>       path: /usr/local/miniconda/pkgs/cache/b89cf7bf.json
>       uid: 501
>       gid: 20
> ```

done

**Comment by stemangiola** [comment]
These random errors drive me crazy

**Comment by mblue9** [comment]
Me too! I’m going to leave this for a day or so as might be due to some change github made that will get fixed.

**Comment by mblue9** [comment]
Superseded by https://github.com/stemangiola/tidyseurat/pull/14

**Pull request closed without merging**
