### PR TITLE
Fix colours

### PR DESCRIPTION
**Pull request by mblue9**

### CODE REVIEW

**Comment by stemangiola** [comment]
This repository is hunted!

```Error: Value cannot be null. (Parameter 'ContainerId')```

**Comment by mblue9** [comment]
Haunted? 👻 🎃 Maybe it is 😄 
But I know what that error is I posted an issue here: https://github.com/Bioconductor/bioconductor_docker/issues/17

**Comment by stemangiola** [comment]
Just to make sure. you solved the old error? So we could try to resubmit. 

this issue might be well related just to github

**Comment by mblue9** [comment]
I fixed the error but does CRAN allow NOTEs? as looks like there's still the NOTE about the Bioc packages not available (SingleCellSignalR, dittoseq). Guess because CRAN does have Bioc packages? Are notes ok or do we need to remove those packages?

**Comment by stemangiola** [comment]
No it does not. tomorrow I will try to see if I can drop the ditto package.

**Comment by mblue9** [comment]
I've removed dittoseq from the vignette & readme but do you need the dev folder or can me remove it (what's it for?) as it's used in there.
And do we remove the vignette section with SingleCellSignalR? as that package is also not allowed.

**Comment by stemangiola** [comment]
The dev folder should be not compiled .Rbuildignore. But if it comes to that we can delete it. we can delete the code block s well.

**Comment by mblue9** [comment]
Ok I've left the dev folder. I've removed SingleCellSignalR, think that should fix the notes.

**Comment by stemangiola** [comment]
Amazing @mblue9 ! Thanks. You think the issue with CRAN is fixed? If so I can merge, export and resubmit

**Comment by mblue9** [comment]
Yes I think so as no errors or notes now locally and here with Mac. I'll set up the Linux & Windows checking in the Github actions when I get a chance, might be able to do it today but it was the same error and Note with Linux as with Mac so should be fine if you don't want to wait.

**Comment by stemangiola** [comment]
> I'll set up the Linux & Windows checking in the Github actions when I get a chance

That would be amazing. I was submitting the package but I might wait so we are really sure.

**Comment by mblue9** [comment]
Done here https://github.com/stemangiola/tidyseurat/pull/14

**Pull request merged**
