### PR TITLE
Some edits

### PR DESCRIPTION
**Pull request by mblue9**
This adds the changes I made to tidySCE to fix the join_transcripts documentation and the vignette changes if you want them here
Also added the man/fragments method to share content across vignette & README as it's just BiocCheck that doesn't like it afaik

### CODE REVIEW

**Comment by stemangiola** [comment]
> 
> 
> This adds the changes I made to tidySCE to fix the join_transcripts documentation and the vignette changes if you want them here
> Also added the man/fragments method to share content across vignette & README as it's just BiocCheck that doesn't like it afaik

Thanks! I'm looking forward to that trick to work!

**Comment by mblue9** [comment]
>Thanks! I'm looking forward to that trick to work!

Well it will probably fail here due to the actions file used here as that one is for developing Bioconductor packages and has the BiocCheck https://github.com/stemangiola/tidyseurat/blob/master/.github/workflows/check-bioc.yml#L208. We could change to use a GitHub actions that's more suited for CRAN packages?

**Comment by stemangiola** [comment]
Sure! If it works we could apply this framework to all the other CRAN packages

**Comment by mblue9** [comment]
Ok cool. I’ll have a look at changing the actions this weekend or when I get a chance.

**Comment by stemangiola** [comment]
I don't understand why this does not trigger github actions. The instructions clearly say

```
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    - dev
```

**Comment by mblue9** [comment]
Not sure why it's not working here yet as it worked locally. Might be formatting in the file. I'll have another look later.

**Comment by mblue9** [comment]
This has passed here now and can be merged if you're happy with it.

**Comment by stemangiola** [comment]
> 
> 
> This has passed here now and can be merged if you're happy with it.

This means that you managed to integrate vignette and README. You are super!

**Comment by stemangiola** [comment]
So strange, was working before and when merged gives error. It could be trivial.

**Comment by mblue9** [comment]
The final test was whether the pkgdown website would build ok which only happens with the merge to master. IAs you saw it didn't but I think this will fix the fail https://github.com/stemangiola/tidyseurat/pulls

**Pull request merged**
